### ISSUE TITLE
Error on shutdown - "this.discordHandle" is null"

### ISSUE THREAD

**Issue by RphCos** [SouprP/Banker-Reworked#1]
Hello,

I have this error when stopping the server : 
"java.lang.NullPointerException: Cannot invoke "me.souprpk.main.Systems.Discord.DiscordHandle.getJda()" because "this.discordHandle" is null".

Obviously, discord is disabled and not set up on my server, I think that's why I have this small issue that has no real impact, except giving the false positive "Error occurred while disabling Banker v2.0 (Is it up to date?)". 

I'm running PaperMC git-Paper-207 (MC: 1.18.1) if it is of any help, and yes, I would understand it not being officially supported

Also, the link to this very page from the Spigot or Bukkit page is broken :) 

Thank you for your work and have a good day.

**Comment by SouprP** [comment]
Hi, thanks for reprorting the issue, I'will check if I get the same error on my server. Does this behaviour of the plugin happens every time the server loads or just from time to time?

**Comment by RphCos** [comment]
Hello,
 
I retested it today and I can confirm, on both my environment running approximatively the same plugins I have the same error each time I stop the server.

Again this little bug is not blocking by any means.

**Comment by SouprP** [comment]
Hello!

The issue has been fixed. An update including the fix and new features will drop in a next few days.

Thank you again for reporting the issue and have a nice day!
