### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by EneruLogia** [SouprP/Banker-Reworked#2]
22.03 05:22:30 [Server] WARN java.io.IOException: No such file or directory
22.03 05:22:30 [Server] WARN at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
22.03 05:22:30 [Server] WARN at java.base/java.io.File.createNewFile(File.java:1043)
22.03 05:22:30 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Systems.Logging.Logging.log(Logging.java:36)
22.03 05:22:30 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Tools.Transaction.handleDeposit(Transaction.java:40)
22.03 05:22:30 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Tools.Transaction.<init>(Transaction.java:30)
22.03 05:22:30 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Events.InventoryEvent.onClick(InventoryEvent.java:71)
22.03 05:22:30 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor306.execute(Unknown Source)
22.03 05:22:30 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
22.03 05:22:30 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
22.03 05:22:30 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
22.03 05:22:30 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
22.03 05:22:30 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2860)
22.03 05:22:30 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
22.03 05:22:30 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
22.03 05:22:30 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
22.03 05:22:30 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
22.03 05:22:30 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
22.03 05:22:30 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
22.03 05:22:30 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
22.03 05:22:30 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1503)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
22.03 05:22:30 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
22.03 05:22:30 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
22.03 05:22:35 [Server] INFO Sending 1 analytic events
22.03 05:22:36 [Server] INFO Fetching all due players...
22.03 05:22:36 [Server] INFO Fetched due players (0 found).
22.03 05:22:37 [Server] WARN java.io.IOException: No such file or directory
22.03 05:22:37 [Server] WARN at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
22.03 05:22:37 [Server] WARN at java.base/java.io.File.createNewFile(File.java:1043)
22.03 05:22:37 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Systems.Logging.Logging.log(Logging.java:36)
22.03 05:22:37 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Tools.Transaction.handleWithdraw(Transaction.java:55)
22.03 05:22:37 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Tools.Transaction.<init>(Transaction.java:31)
22.03 05:22:37 [Server] WARN at Banker-v2.0+pre-release+3.jar//me.souprpk.main.Events.InventoryEvent.onClick(InventoryEvent.java:110)
22.03 05:22:37 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor306.execute(Unknown Source)
22.03 05:22:37 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
22.03 05:22:37 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
22.03 05:22:37 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
22.03 05:22:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
22.03 05:22:37 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2860)
22.03 05:22:37 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
22.03 05:22:37 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
22.03 05:22:37 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
22.03 05:22:37 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
22.03 05:22:37 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
22.03 05:22:37 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
22.03 05:22:37 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
22.03 05:22:37 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
22.03 05:22:37 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
22.03 05:22:37 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SouprP** [comment]
Hello! What version of MC and Paper are you using?

**Comment by SouprP** [comment]
Ok, so this probably happened because the logs folder did not get created or you deleted it. The log folder gets created on start / reload of the server, so that's probably why got this error. 

So just reload your server and it should create the logs folder.
Have a nice day!
